#登陆相关配置
login:
  #开放的模拟登陆api服务器地址
  api: "请自建"
#用户组配置
users:
  #单个用户配置
  - user:
      #username 学号
      username: '********'
      #password 密码
      password: '********'
      #address 地址，定位信息
      address: xxxxxxxxxx
      #钉钉机器人得token和secret，机器人设置选择加签。
      token: b41c9061498b2bc**************************aa1cd0e76c5440dd467
      secret: SEC1a0a856c550***************************b18678b45ee081a7d25648b979a
      #school 学校全称
      school: 宁波大学
      #获取经度纬度链接http://api.map.baidu.com/lbsapi/getpoint/index.html
      #lon 经度
      lon: 123.456789
      #lat 纬度
      lat: 12.358468

#今日校园相关配置
cpdaily:
  #附加信息组默认选项配置，没有可留空
  defaults:
    - default:
        title: 今日您的健康情况是?（如有发热等呼吸道症状，请第一时间报备辅导员）
        value: A.健康
    #附加信息组默认选项配置，按顺序，可留空
    - default:
#        #表单项标题
        title: 今日您的甬行码颜色是？
#        #表单项默认值
        value: A.绿色

    - default:
#        #表单项标题
        title: 今日您是否存在其他异常情况？
#        #表单项默认值
        value: A.无

    - default:
#        #表单项标题
        title: 明日你是否有出行计划（离开居住地所在市）
#        #表单项默认值
        value: 否